//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jlab.FileTransferServer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Todas")]
        public string AllTrace {
            get {
                return ((string)(this["AllTrace"]));
            }
            set {
                this["AllTrace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Directorios")]
        public string Directory {
            get {
                return ((string)(this["Directory"]));
            }
            set {
                this["Directory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ficheros")]
        public string Files {
            get {
                return ((string)(this["Files"]));
            }
            set {
                this["Files"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Miniaturas")]
        public string Thumbnails {
            get {
                return ((string)(this["Thumbnails"]));
            }
            set {
                this["Thumbnails"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Indice")]
        public string Index {
            get {
                return ((string)(this["Index"]));
            }
            set {
                this["Index"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Corriendo")]
        public string Running {
            get {
                return ((string)(this["Running"]));
            }
            set {
                this["Running"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Detenido")]
        public string Stoped {
            get {
                return ((string)(this["Stoped"]));
            }
            set {
                this["Stoped"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Configuración")]
        public string Setting {
            get {
                return ((string)(this["Setting"]));
            }
            set {
                this["Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tamaño de Buffer")]
        public string BufferSize {
            get {
                return ((string)(this["BufferSize"]));
            }
            set {
                this["BufferSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Iniciar Servidor")]
        public string StartServer {
            get {
                return ((string)(this["StartServer"]));
            }
            set {
                this["StartServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Detener Servidor")]
        public string StopServer {
            get {
                return ((string)(this["StopServer"]));
            }
            set {
                this["StopServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cargar Directorio")]
        public string LoadDir {
            get {
                return ((string)(this["LoadDir"]));
            }
            set {
                this["LoadDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Indice de Miniaturas")]
        public string ThumbIndex {
            get {
                return ((string)(this["ThumbIndex"]));
            }
            set {
                this["ThumbIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cant. Trazas a Listar")]
        public string CountTraceList {
            get {
                return ((string)(this["CountTraceList"]));
            }
            set {
                this["CountTraceList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Concurrencia (Cant. Máx. a Servir en Paralelo)")]
        public string Concurrence {
            get {
                return ((string)(this["Concurrence"]));
            }
            set {
                this["Concurrence"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Crear")]
        public string Create {
            get {
                return ((string)(this["Create"]));
            }
            set {
                this["Create"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cargar")]
        public string Load {
            get {
                return ((string)(this["Load"]));
            }
            set {
                this["Load"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Imagen de Presentación")]
        public string PresImage {
            get {
                return ((string)(this["PresImage"]));
            }
            set {
                this["PresImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Salir")]
        public string Close {
            get {
                return ((string)(this["Close"]));
            }
            set {
                this["Close"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Guardar")]
        public string Saving {
            get {
                return ((string)(this["Saving"]));
            }
            set {
                this["Saving"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cancelar")]
        public string Cancel {
            get {
                return ((string)(this["Cancel"]));
            }
            set {
                this["Cancel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Opciones")]
        public string Options {
            get {
                return ((string)(this["Options"]));
            }
            set {
                this["Options"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pregunta")]
        public string Question {
            get {
                return ((string)(this["Question"]));
            }
            set {
                this["Question"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("¿El directorio elegido ya posee índice de miniaturas, desea actualizar dicho índi" +
            "ce?")]
        public string UpdateThumbIndex {
            get {
                return ((string)(this["UpdateThumbIndex"]));
            }
            set {
                this["UpdateThumbIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("¿El directorio elegido no posee índice de miniaturas, desea crear su índice?")]
        public string CreateThumbIndex {
            get {
                return ((string)(this["CreateThumbIndex"]));
            }
            set {
                this["CreateThumbIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Seleccione la Carpeta o Unidad a Indizar.")]
        public string DirectoryToIndex {
            get {
                return ((string)(this["DirectoryToIndex"]));
            }
            set {
                this["DirectoryToIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Seleccione la Carpeta o Unidad que será compartida.")]
        public string DirectoryToShare {
            get {
                return ((string)(this["DirectoryToShare"]));
            }
            set {
                this["DirectoryToShare"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El Directorio")]
        public string TheDirectory {
            get {
                return ((string)(this["TheDirectory"]));
            }
            set {
                this["TheDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("no existe")]
        public string NotExist {
            get {
                return ((string)(this["NotExist"]));
            }
            set {
                this["NotExist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Detener")]
        public string Stop {
            get {
                return ((string)(this["Stop"]));
            }
            set {
                this["Stop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Total")]
        public string Total {
            get {
                return ((string)(this["Total"]));
            }
            set {
                this["Total"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Continuar")]
        public string Continue {
            get {
                return ((string)(this["Continue"]));
            }
            set {
                this["Continue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("¿Desea detener la creación del índice?")]
        public string StopIndexCreation {
            get {
                return ((string)(this["StopIndexCreation"]));
            }
            set {
                this["StopIndexCreation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("No se pudo cargar la imagen de presentación, el fichero seleccionado no es una im" +
            "agen.")]
        public string NotLoadPresImage {
            get {
                return ((string)(this["NotLoadPresImage"]));
            }
            set {
                this["NotLoadPresImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Error")]
        public string Error {
            get {
                return ((string)(this["Error"]));
            }
            set {
                this["Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Miniatura renombrada para Fichero renombrado de")]
        public string RenamedThumb {
            get {
                return ((string)(this["RenamedThumb"]));
            }
            set {
                this["RenamedThumb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Miniatura actualizada para Fichero renombrado de")]
        public string UpdateThumb {
            get {
                return ((string)(this["UpdateThumb"]));
            }
            set {
                this["UpdateThumb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("a")]
        public string To {
            get {
                return ((string)(this["To"]));
            }
            set {
                this["To"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Miniatura creada para el Fichero")]
        public string CreateThumb {
            get {
                return ((string)(this["CreateThumb"]));
            }
            set {
                this["CreateThumb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Miniatura eliminada para el antiguo Fichero")]
        public string DeleteThumb {
            get {
                return ((string)(this["DeleteThumb"]));
            }
            set {
                this["DeleteThumb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("que desea compartir no existe.")]
        public string ShareNotExist {
            get {
                return ((string)(this["ShareNotExist"]));
            }
            set {
                this["ShareNotExist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Imposible iniciar el Servidor.")]
        public string NotCanStartServer {
            get {
                return ((string)(this["NotCanStartServer"]));
            }
            set {
                this["NotCanStartServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Directorio no válido")]
        public string InvalidDir {
            get {
                return ((string)(this["InvalidDir"]));
            }
            set {
                this["InvalidDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Creando Indice de miniaturas...")]
        public string CreatingThumbIndex {
            get {
                return ((string)(this["CreatingThumbIndex"]));
            }
            set {
                this["CreatingThumbIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Creación Finalizada.")]
        public string CreatingFinish {
            get {
                return ((string)(this["CreatingFinish"]));
            }
            set {
                this["CreatingFinish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Creación Interrumpida.")]
        public string CreatingInterrupted {
            get {
                return ((string)(this["CreatingInterrupted"]));
            }
            set {
                this["CreatingInterrupted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Eliminando")]
        public string Deleting {
            get {
                return ((string)(this["Deleting"]));
            }
            set {
                this["Deleting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("todas")]
        public string All {
            get {
                return ((string)(this["All"]));
            }
            set {
                this["All"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("para directorio")]
        public string ForDirectory {
            get {
                return ((string)(this["ForDirectory"]));
            }
            set {
                this["ForDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Eliminación completada")]
        public string DeletingFinished {
            get {
                return ((string)(this["DeletingFinished"]));
            }
            set {
                this["DeletingFinished"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Miniatura añadida para fichero")]
        public string AddedThumb {
            get {
                return ((string)(this["AddedThumb"]));
            }
            set {
                this["AddedThumb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El puerto del servidor cambia con esta configuración, para completar debe reinici" +
            "ar el Servidor, ¿desea continuar?")]
        public string PortChange {
            get {
                return ((string)(this["PortChange"]));
            }
            set {
                this["PortChange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("¿Está seguro que desea cerrar la aplicación?")]
        public string ClosingMsg {
            get {
                return ((string)(this["ClosingMsg"]));
            }
            set {
                this["ClosingMsg"] = value;
            }
        }
    }
}
